CREATE DATABASE `300match`; /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */

CREATE TABLE `matches` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `match_id` varchar(255) DEFAULT NULL,
  `match_id_int` bigint DEFAULT NULL COMMENT 'int id',
  `m_id` int DEFAULT NULL COMMENT '比赛类型',
  `used_time` int DEFAULT NULL COMMENT '所用时间',
  `create_time` int DEFAULT NULL COMMENT '游戏结束时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `match_id` (`match_id`),
  KEY `create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1453150 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='比赛表';

CREATE TABLE `players` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `match_id` varchar(255) NOT NULL COMMENT '比赛id',
  `player_id` bigint NOT NULL COMMENT '玩家id',
  `name` varchar(255) NOT NULL COMMENT '玩家昵称',
  `hero_id` int NOT NULL COMMENT '所选英雄id',
  `hero_lv` int NOT NULL COMMENT '结束时英雄等级',
  `side` int NOT NULL COMMENT '1-左下，2-右上',
  `result` int NOT NULL COMMENT '输赢：1-赢，2-输',
  `first_win` int NOT NULL COMMENT '是否首胜：0-否，1-是',
  `summoner_skill1` int NOT NULL COMMENT 'd技能',
  `summoner_skill2` int NOT NULL COMMENT 'f技能',
  `total_money` int NOT NULL COMMENT '结束时经济',
  `kill_unit` int NOT NULL COMMENT '补刀数',
  `used_time` int NOT NULL COMMENT '所用时间',
  `kill_player` int NOT NULL COMMENT '击杀',
  `death` int NOT NULL COMMENT '死亡',
  `assist` int NOT NULL COMMENT '助攻',
  `con_kill_max` int NOT NULL COMMENT '未知',
  `mul_kill_max` int NOT NULL COMMENT '未知',
  `destory_tower` int NOT NULL COMMENT '推塔',
  `treat` int NOT NULL COMMENT '未知',
  `put_eyes` int NOT NULL COMMENT '插眼数',
  `destory_eyes` int NOT NULL COMMENT '排眼数',
  `elo` int NOT NULL COMMENT '竞技力（已废弃',
  `fv` int NOT NULL COMMENT '竞技力',
  `total_money_side` int NOT NULL COMMENT '己方总经济',
  `total_money_percent` double NOT NULL COMMENT '个人经济占比',
  `make_damage_side` int NOT NULL COMMENT '己方总伤害',
  `make_damage_percent` double NOT NULL COMMENT '个人伤害占比',
  `take_damage_side` int NOT NULL COMMENT '己方总承伤',
  `take_damage_percent` double NOT NULL COMMENT '个人承伤占比',
  `damage_conversion_rate` double NOT NULL COMMENT '伤害转换率',
  `create_time` int NOT NULL COMMENT '游戏结束时间戳',
  PRIMARY KEY (`id`),
  KEY `player_id` (`player_id`),
  KEY `create_time` (`create_time`),
  KEY `match_id` (`match_id`),
  KEY `create_time_and_hero_id` (`create_time`,`hero_id`)
) ENGINE=InnoDB AUTO_INCREMENT=20305458 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;