cqhttp: 127.0.0.1:8083
access-token: 114514
dev: false

analysis:
  mysql:
    addr: localhost:3306
    user: root
    password: root@1234
    databse: 300match
  redis:
    addr: localhost:6379
    db: 0
