cqhttp: 127.0.0.1:8083
access-token: 114514
dev: false
auto-collect: 
  run: true
  start: 0
  end: 9
  log: ./crawl.log

analysis:
  mysql:
    addr: localhost:3306
    user: root
    password: root@1234
    databse: 300match
  redis:
    addr: localhost:8089
    password: root@1234
    db: 0
